[package]
name = "mpc"
version = "0.1.10"
description = "WIP bindings for orangeduck's mpc (Micro Parser Combinators) library"
authors = ["Lukáš Hozda <luk.hozda@gmail.com>"]
build = "build.rs"
license = "Fair"
repository = "https://github.com/c2hub/mpc-rs"

[build-dependencies]
gcc = "0.3"
